In [ ]:
import numpy as np
import pandas as pd

x = np.array([2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 21., 11., 1.5, 1.1])
y = np.array([2.4, 0.7, 2.9, 2.2, 3.0, 2.7, 6.0, 1.0, 1.6, 0.9])
mat = np.transpose(np.vstack((x, y)))
df = pd.DataFrame(mat, columns=['x', 'y'])

print('The dataset:')
print(df)

print("\nPart 1 : Standardization of Data\n")

mean = df.mean()
std = df.std()
print(f'The mean: \n{mean}\n')
print(f'The standard deviation: \n{std}\n')
data_standardized = (df - mean) / std
print(f'The standardized dataset: \n{data_standardized}\n')

print("\nPart 2 : Compute Covariance Matrix\n")

cov_matrix = np.cov(data_standardized.to_numpy().T, ddof=0)
print(f'The covariance matrix: \n{cov_matrix}\n')

print("\nPart 3 : Compute Eigenvalue and Eigenvector\n")

eigen_value, eigen_vector = np.linalg.eig(cov_matrix)
print(f'Eigen values: {eigen_value}')
print(f'Eigen vectors: \n{eigen_vector}\n')


print("\nPart 4 : Sort the Eigenvalue and Eigenvector\n")

i = eigen_value.argsort()[::-1]
eigen_value, eigen_vector = eigen_value[i], eigen_vector[i]
print(f'Sort in Descending Order\nEigen values: {eigen_value}\nEigen vectors: \n{eigen_vector}\n')


print("\nPart 5 : Transform to Original Matrix\n")

def transform(matrix, eigen_vector, k):
    return np.dot(matrix, eigen_vector[:, :k])

k = 1
print(f'Pick top {k} Eigenvalue\n')
print(f'Original: \n{df.to_numpy()}\n')
transformed = transform(data_standardized, eigen_vector, k)
print(f'Transformed matrix ({k} PC): \n{transformed}\n')

The dataset:
      x    y
0   2.5  2.4
1   0.5  0.7
2   2.2  2.9
3   1.9  2.2
4   3.1  3.0
5   2.3  2.7
6  21.0  6.0
7  11.0  1.0
8   1.5  1.6
9   1.1  0.9

Part 1 : Standardization of Data

The mean: 
x    4.71
y    2.34
dtype: float64

The standard deviation: 
x    6.441782
y    1.542149
dtype: float64

The standardized dataset: 
          x         y
0 -0.343073  0.038907
1 -0.653546 -1.063451
2 -0.389644  0.363130
3 -0.436215 -0.090782
4 -0.249931  0.427974
5 -0.374120  0.233441
6  2.528803  2.373312
7  0.976438 -0.868918
8 -0.498309 -0.479850
9 -0.560404 -0.933762


Part 2 : Compute Covariance Matrix

The covariance matrix: 
[[0.9        0.63010705]
 [0.63010705 0.9       ]]


Part 3 : Compute Eigenvalue and Eigenvector

Eigen values: [1.53010705 0.26989295]
Eigen vectors: 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Part 4 : Sort the Eigenvalue and Eigenvector

Sort in Descending Order
Eigen values: [1.53010705 0.26989295]
Eigen vectors: 
[[ 0.70710678 -0.70710678]
 